//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InverGrove.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InverGrove.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddRange called on LogServiceEventArgs with an empty enumerable. This exception was added simply as a notice that the attempt to log multiple exceptions has failed, catastrophically..
        /// </summary>
        public static string AddRangeFailed {
            get {
                return ResourceManager.GetString("AddRangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address length is invalid. Must be between 1 and 200 characters..
        /// </summary>
        public static string AddressLengthErrorMessage {
            get {
                return ResourceManager.GetString("AddressLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required..
        /// </summary>
        public static string AddressOneRequired {
            get {
                return ResourceManager.GetString("AddressOneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application name is too long..
        /// </summary>
        public static string ApplicationNameTooLong {
            get {
                return ResourceManager.GetString("ApplicationNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code is invalid..
        /// </summary>
        public static string AreaCodeInvalidErrorMessage {
            get {
                return ResourceManager.GetString("AreaCodeInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code is required..
        /// </summary>
        public static string AreaCodeRequired {
            get {
                return ResourceManager.GetString("AreaCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinRequiredNonalphanumericCharacters can not be more than MinRequiredPasswordLength.
        /// </summary>
        public static string CanNotBeMoreThanMinRequiredPasswordLength {
            get {
                return ResourceManager.GetString("CanNotBeMoreThanMinRequiredPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider cannot retrieve a hashed password.
        /// </summary>
        public static string CannotRetrieveHashedPassword {
            get {
                return ResourceManager.GetString("CannotRetrieveHashedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider cannot retrieve a hashed password.
        /// </summary>
        public static string CannotRetrieveHashedPassword1 {
            get {
                return ResourceManager.GetString("CannotRetrieveHashedPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must contain a minimum of {0} numeric characters..
        /// </summary>
        public static string ChangePasswordDoesNotContainNumber {
            get {
                return ResourceManager.GetString("ChangePasswordDoesNotContainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must contain a minimum of {0} non alphanumeric characters..
        /// </summary>
        public static string ChangePasswordDoesNotContainSymbol {
            get {
                return ResourceManager.GetString("ChangePasswordDoesNotContainSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password does not meet requirements. Must be a minimum of {0} characters.
        /// </summary>
        public static string ChangePasswordDoesNotMeetRequirements {
            get {
                return ResourceManager.GetString("ChangePasswordDoesNotMeetRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not meet the requirements for a password. Ensure there are no spaces, and only contains letters numbers or one of the following characters: ! @ # $ % ^.
        /// </summary>
        public static string ChangePasswordNotCorrect {
            get {
                return ResourceManager.GetString("ChangePasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password and new password cannot be the same..
        /// </summary>
        public static string ChangePasswordSameWord {
            get {
                return ResourceManager.GetString("ChangePasswordSameWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City length is invalid.  Must be between 1 and 100 characters..
        /// </summary>
        public static string CityLengthErrorMessage {
            get {
                return ResourceManager.GetString("CityLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required..
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ConfirmPasswordErrorMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string CreateMemberProviderError {
            get {
                return ResourceManager.GetString("CreateMemberProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string CreateMemberUnknownErorr {
            get {
                return ResourceManager.GetString("CreateMemberUnknownErorr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string CreateMemberUserRejected {
            get {
                return ResourceManager.GetString("CreateMemberUserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LogService defaultLog has been created and enabled..
        /// </summary>
        public static string DefaultLogCreated {
            get {
                return ResourceManager.GetString("DefaultLogCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user name for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string DuplicateUserEmail {
            get {
                return ResourceManager.GetString("DuplicateUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That username has been claimed already. Please enter a different username..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EmailRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EmailRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogService - Error log request made, but message contained no data..
        /// </summary>
        public static string ErrorMessageEmpty {
            get {
                return ResourceManager.GetString("ErrorMessageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogService - Fatal log request made, but message contained no data..
        /// </summary>
        public static string FatalLogMessageEmpty {
            get {
                return ResourceManager.GetString("FatalLogMessageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum characters is 50..
        /// </summary>
        public static string FirstLastNameLengthError {
            get {
                return ResourceManager.GetString("FirstLastNameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is required..
        /// </summary>
        public static string GenderRequiredErrorMessage {
            get {
                return ResourceManager.GetString("GenderRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url not set.
        /// </summary>
        public static string HttpMessageEventArgsUrlNotSet {
            get {
                return ResourceManager.GetString("HttpMessageEventArgsUrlNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string IncorrectPasswordErrorMessage {
            get {
                return ResourceManager.GetString("IncorrectPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid application name..
        /// </summary>
        public static string InvalidApplicationName {
            get {
                return ResourceManager.GetString("InvalidApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidPasswordAnswer {
            get {
                return ResourceManager.GetString("InvalidPasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidPasswordQuestion {
            get {
                return ResourceManager.GetString("InvalidPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select whether or not to create a user account..
        /// </summary>
        public static string IsUserRequired {
            get {
                return ResourceManager.GetString("IsUserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogService - Request sent to {0}(Exception ex), however the Exception object was null..
        /// </summary>
        public static string LogExceptionNull {
            get {
                return ResourceManager.GetString("LogExceptionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Marital Status..
        /// </summary>
        public static string MaritalStatusRequiredErrorMessage {
            get {
                return ResourceManager.GetString("MaritalStatusRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom password validation failed..
        /// </summary>
        public static string MembershipCustomPasswordValidationFailure {
            get {
                return ResourceManager.GetString("MembershipCustomPasswordValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom password validation failed..
        /// </summary>
        public static string MembershipCustomPasswordValidationFailure1 {
            get {
                return ResourceManager.GetString("MembershipCustomPasswordValidationFailure1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniumum alphanumeric character value of {0} is invalid.  Minumum number of alphanumeric characters must be between 0 and {1}..
        /// </summary>
        public static string MembershipMinRequiredNonAlphanumericCharactersIncorrect {
            get {
                return ResourceManager.GetString("MembershipMinRequiredNonAlphanumericCharactersIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniumum alphanumeric character value of {0} is invalid.  Minumum number of alphanumeric characters must be between 0 and {1}..
        /// </summary>
        public static string MembershipMinRequiredNonAlphanumericCharactersIncorrect1 {
            get {
                return ResourceManager.GetString("MembershipMinRequiredNonAlphanumericCharactersIncorrect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length of {0} is invalid.  Password length must be between 1 and 128..
        /// </summary>
        public static string MembershipPasswordLengthIncorrect {
            get {
                return ResourceManager.GetString("MembershipPasswordLengthIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Membership Provider has not been configured to support password retrieval..
        /// </summary>
        public static string MembershipPasswordRetrievalNotSupported {
            get {
                return ResourceManager.GetString("MembershipPasswordRetrievalNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This provider is not configured to allow password resets. To enable password reset, set enablePasswordReset to \&quot;true\&quot; in the configuration file..
        /// </summary>
        public static string NotConfiguredToSupportPasswordResets {
            get {
                return ResourceManager.GetString("NotConfiguredToSupportPasswordResets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null exception object sent to DebugLog..
        /// </summary>
        public static string NullExceptionObject {
            get {
                return ResourceManager.GetString("NullExceptionObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// This method is a member of {0}..
        /// </summary>
        public static string ParameterNullExceptionMessageObjectIs {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMessageObjectIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} on method {1}..
        /// </summary>
        public static string ParameterNullExceptionMessageOnMethod {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMessageOnMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method expected a non-null, or non-default-value of the type {0}..
        /// </summary>
        public static string ParameterNullExceptionMethodExpectedNonNull {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMethodExpectedNonNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  No parameter name passed, however the following parameters were available at the time the exception was thrown:
        ///.
        /// </summary>
        public static string ParameterNullExceptionNoName {
            get {
                return ResourceManager.GetString("ParameterNullExceptionNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unable to determine the failing parameter type, perhaps the name passed was incorrect? .
        /// </summary>
        public static string ParameterNullExceptionUnableToDetermine {
            get {
                return ResourceManager.GetString("ParameterNullExceptionUnableToDetermine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unable to determine the method&apos;s declaring type..
        /// </summary>
        public static string ParameterNullExceptionUnableToDetermineDeclaringType {
            get {
                return ResourceManager.GetString("ParameterNullExceptionUnableToDetermineDeclaringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is too long: it must not exceed {1} chars in length..
        /// </summary>
        public static string ParameterTooLong {
            get {
                return ResourceManager.GetString("ParameterTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of parameter &apos;{0}&apos; needs to be greater or equal to &apos;{1}&apos;..
        /// </summary>
        public static string ParameterTooShort {
            get {
                return ResourceManager.GetString("ParameterTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string PasswordErrorMessage {
            get {
                return ResourceManager.GetString("PasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password strength regular expression: {0}
        ///.
        /// </summary>
        public static string PasswordRegexStrength {
            get {
                return ResourceManager.GetString("PasswordRegexStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Person Type..
        /// </summary>
        public static string PersonTypeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PersonTypeRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number format is invalid..
        /// </summary>
        public static string PhoneNumberFormatErrorMessage {
            get {
                return ResourceManager.GetString("PhoneNumberFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number required..
        /// </summary>
        public static string PhoneNumberRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PhoneNumberRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a phone number type..
        /// </summary>
        public static string PhoneNumberTypeRequired {
            get {
                return ResourceManager.GetString("PhoneNumberTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code format is invalid..
        /// </summary>
        public static string PostalCodeInvalidErrorMessage {
            get {
                return ResourceManager.GetString("PostalCodeInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code is length is invalid. Must be between 5 and 10 characters..
        /// </summary>
        public static string PostalCodeLengthErrorMessage {
            get {
                return ResourceManager.GetString("PostalCodeLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code is required..
        /// </summary>
        public static string PostalCodeRequired {
            get {
                return ResourceManager.GetString("PostalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a property called &apos;{0}&apos; on type {1}.
        /// </summary>
        public static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security answer is incorrect. Please re-enter..
        /// </summary>
        public static string SecurityAnswerIncorrect {
            get {
                return ResourceManager.GetString("SecurityAnswerIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security answer {0} is invalid..
        /// </summary>
        public static string SecurityAnswerInvalidText {
            get {
                return ResourceManager.GetString("SecurityAnswerInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security answer value cannot exceed 64 characters..
        /// </summary>
        public static string SecurityAnswerMaximumLength {
            get {
                return ResourceManager.GetString("SecurityAnswerMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer missing..
        /// </summary>
        public static string SecurityAnswerMissing {
            get {
                return ResourceManager.GetString("SecurityAnswerMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a security answer..
        /// </summary>
        public static string SecurityAnswerRequired {
            get {
                return ResourceManager.GetString("SecurityAnswerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security question value cannot exceed 64 characters..
        /// </summary>
        public static string SecurityQuestionMaximumLength {
            get {
                return ResourceManager.GetString("SecurityQuestionMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to reset your password online.  Please contact Patterson Medical on 08448 730 035..
        /// </summary>
        public static string SecurityQuestionMissing {
            get {
                return ResourceManager.GetString("SecurityQuestionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a security question..
        /// </summary>
        public static string SecurityQuestionRequired {
            get {
                return ResourceManager.GetString("SecurityQuestionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when attepting to send email message..
        /// </summary>
        public static string SendMailError {
            get {
                return ResourceManager.GetString("SendMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is required..
        /// </summary>
        public static string StateRequired {
            get {
                return ResourceManager.GetString("StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists. Please enter a different user name..
        /// </summary>
        public static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogService - Warning log request made, but message contained no data..
        /// </summary>
        public static string WarnLogMessageEmpty {
            get {
                return ResourceManager.GetString("WarnLogMessageEmpty", resourceCulture);
            }
        }
    }
}
