//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InverGrove.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InverGrove.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application name is too long..
        /// </summary>
        public static string ApplicationNameTooLong {
            get {
                return ResourceManager.GetString("ApplicationNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application name is too long..
        /// </summary>
        public static string ApplicationNameTooLong1 {
            get {
                return ResourceManager.GetString("ApplicationNameTooLong1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinRequiredNonalphanumericCharacters can not be more than MinRequiredPasswordLength.
        /// </summary>
        public static string CanNotBeMoreThanMinRequiredPasswordLength {
            get {
                return ResourceManager.GetString("CanNotBeMoreThanMinRequiredPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinRequiredNonalphanumericCharacters can not be more than MinRequiredPasswordLength.
        /// </summary>
        public static string CanNotBeMoreThanMinRequiredPasswordLength1 {
            get {
                return ResourceManager.GetString("CanNotBeMoreThanMinRequiredPasswordLength1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider cannot retrieve a hashed password.
        /// </summary>
        public static string CannotRetrieveHashedPassword {
            get {
                return ResourceManager.GetString("CannotRetrieveHashedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider cannot retrieve a hashed password.
        /// </summary>
        public static string CannotRetrieveHashedPassword1 {
            get {
                return ResourceManager.GetString("CannotRetrieveHashedPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must contain a minimum of {0} numeric characters..
        /// </summary>
        public static string ChangePasswordDoesNotContainNumber {
            get {
                return ResourceManager.GetString("ChangePasswordDoesNotContainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must contain a minimum of {0} numeric characters..
        /// </summary>
        public static string ChangePasswordDoesNotContainNumber1 {
            get {
                return ResourceManager.GetString("ChangePasswordDoesNotContainNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must contain a minimum of {0} non alphanumeric characters..
        /// </summary>
        public static string ChangePasswordDoesNotContainSymbol {
            get {
                return ResourceManager.GetString("ChangePasswordDoesNotContainSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must contain a minimum of {0} non alphanumeric characters..
        /// </summary>
        public static string ChangePasswordDoesNotContainSymbol1 {
            get {
                return ResourceManager.GetString("ChangePasswordDoesNotContainSymbol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password does not meet requirements. Must be a minimum of {0} characters.
        /// </summary>
        public static string ChangePasswordDoesNotMeetRequirements {
            get {
                return ResourceManager.GetString("ChangePasswordDoesNotMeetRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password does not meet requirements. Must be a minimum of {0} characters.
        /// </summary>
        public static string ChangePasswordDoesNotMeetRequirements1 {
            get {
                return ResourceManager.GetString("ChangePasswordDoesNotMeetRequirements1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not meet the requirements for a password. Ensure there are no spaces, and only contains letters numbers or one of the following characters: ! @ # $ % ^.
        /// </summary>
        public static string ChangePasswordNotCorrect {
            get {
                return ResourceManager.GetString("ChangePasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not meet the requirements for a password. Ensure there are no spaces, and only contains letters numbers or one of the following characters: ! @ # $ % ^.
        /// </summary>
        public static string ChangePasswordNotCorrect1 {
            get {
                return ResourceManager.GetString("ChangePasswordNotCorrect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password and new password cannot be the same..
        /// </summary>
        public static string ChangePasswordSameWord {
            get {
                return ResourceManager.GetString("ChangePasswordSameWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password and new password cannot be the same..
        /// </summary>
        public static string ChangePasswordSameWord1 {
            get {
                return ResourceManager.GetString("ChangePasswordSameWord1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ConfirmPasswordErrorMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ConfirmPasswordErrorMessage1 {
            get {
                return ResourceManager.GetString("ConfirmPasswordErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string IncorrectPasswordErrorMessage {
            get {
                return ResourceManager.GetString("IncorrectPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string IncorrectPasswordErrorMessage1 {
            get {
                return ResourceManager.GetString("IncorrectPasswordErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid application name..
        /// </summary>
        public static string InvalidApplicationName {
            get {
                return ResourceManager.GetString("InvalidApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid application name..
        /// </summary>
        public static string InvalidApplicationName1 {
            get {
                return ResourceManager.GetString("InvalidApplicationName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom password validation failed..
        /// </summary>
        public static string MembershipCustomPasswordValidationFailure {
            get {
                return ResourceManager.GetString("MembershipCustomPasswordValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom password validation failed..
        /// </summary>
        public static string MembershipCustomPasswordValidationFailure1 {
            get {
                return ResourceManager.GetString("MembershipCustomPasswordValidationFailure1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniumum alphanumeric character value of {0} is invalid.  Minumum number of alphanumeric characters must be between 0 and {1}..
        /// </summary>
        public static string MembershipMinRequiredNonAlphanumericCharactersIncorrect {
            get {
                return ResourceManager.GetString("MembershipMinRequiredNonAlphanumericCharactersIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniumum alphanumeric character value of {0} is invalid.  Minumum number of alphanumeric characters must be between 0 and {1}..
        /// </summary>
        public static string MembershipMinRequiredNonAlphanumericCharactersIncorrect1 {
            get {
                return ResourceManager.GetString("MembershipMinRequiredNonAlphanumericCharactersIncorrect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length of {0} is invalid.  Password length must be between 1 and 128..
        /// </summary>
        public static string MembershipPasswordLengthIncorrect {
            get {
                return ResourceManager.GetString("MembershipPasswordLengthIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length of {0} is invalid.  Password length must be between 1 and 128..
        /// </summary>
        public static string MembershipPasswordLengthIncorrect1 {
            get {
                return ResourceManager.GetString("MembershipPasswordLengthIncorrect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Membership Provider has not been configured to support password retrieval..
        /// </summary>
        public static string MembershipPasswordRetrievalNotSupported {
            get {
                return ResourceManager.GetString("MembershipPasswordRetrievalNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Membership Provider has not been configured to support password retrieval..
        /// </summary>
        public static string MembershipPasswordRetrievalNotSupported1 {
            get {
                return ResourceManager.GetString("MembershipPasswordRetrievalNotSupported1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This provider is not configured to allow password resets. To enable password reset, set enablePasswordReset to \&quot;true\&quot; in the configuration file..
        /// </summary>
        public static string NotConfiguredToSupportPasswordResets {
            get {
                return ResourceManager.GetString("NotConfiguredToSupportPasswordResets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This provider is not configured to allow password resets. To enable password reset, set enablePasswordReset to \&quot;true\&quot; in the configuration file..
        /// </summary>
        public static string NotConfiguredToSupportPasswordResets1 {
            get {
                return ResourceManager.GetString("NotConfiguredToSupportPasswordResets1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// This method is a member of {0}..
        /// </summary>
        public static string ParameterNullExceptionMessageObjectIs {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMessageObjectIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} on method {1}..
        /// </summary>
        public static string ParameterNullExceptionMessageOnMethod {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMessageOnMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method expected a non-null, or non-default-value of the type {0}..
        /// </summary>
        public static string ParameterNullExceptionMethodExpectedNonNull {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMethodExpectedNonNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  No parameter name passed, however the following parameters were available at the time the exception was thrown:
        ///.
        /// </summary>
        public static string ParameterNullExceptionNoName {
            get {
                return ResourceManager.GetString("ParameterNullExceptionNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unable to determine the failing parameter type, perhaps the name passed was incorrect? .
        /// </summary>
        public static string ParameterNullExceptionUnableToDetermine {
            get {
                return ResourceManager.GetString("ParameterNullExceptionUnableToDetermine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unable to determine the method&apos;s declaring type..
        /// </summary>
        public static string ParameterNullExceptionUnableToDetermineDeclaringType {
            get {
                return ResourceManager.GetString("ParameterNullExceptionUnableToDetermineDeclaringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is too long: it must not exceed {1} chars in length..
        /// </summary>
        public static string ParameterTooLong {
            get {
                return ResourceManager.GetString("ParameterTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is too long: it must not exceed {1} chars in length..
        /// </summary>
        public static string ParameterTooLong1 {
            get {
                return ResourceManager.GetString("ParameterTooLong1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of parameter &apos;{0}&apos; needs to be greater or equal to &apos;{1}&apos;..
        /// </summary>
        public static string ParameterTooShort {
            get {
                return ResourceManager.GetString("ParameterTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of parameter &apos;{0}&apos; needs to be greater or equal to &apos;{1}&apos;..
        /// </summary>
        public static string ParameterTooShort1 {
            get {
                return ResourceManager.GetString("ParameterTooShort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string PasswordErrorMessage {
            get {
                return ResourceManager.GetString("PasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string PasswordErrorMessage1 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password strength regular expression: {0}
        ///.
        /// </summary>
        public static string PasswordRegexStrength {
            get {
                return ResourceManager.GetString("PasswordRegexStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password strength regular expression: {0}
        ///.
        /// </summary>
        public static string PasswordRegexStrength1 {
            get {
                return ResourceManager.GetString("PasswordRegexStrength1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a property called &apos;{0}&apos; on type {1}.
        /// </summary>
        public static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a property called &apos;{0}&apos; on type {1}.
        /// </summary>
        public static string PropertyNotFound1 {
            get {
                return ResourceManager.GetString("PropertyNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security answer is incorrect. Please re-enter..
        /// </summary>
        public static string SecurityAnswerIncorrect {
            get {
                return ResourceManager.GetString("SecurityAnswerIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security answer is incorrect. Please re-enter..
        /// </summary>
        public static string SecurityAnswerIncorrect1 {
            get {
                return ResourceManager.GetString("SecurityAnswerIncorrect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security answer {0} is invalid..
        /// </summary>
        public static string SecurityAnswerInvalidText {
            get {
                return ResourceManager.GetString("SecurityAnswerInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security answer {0} is invalid..
        /// </summary>
        public static string SecurityAnswerInvalidText1 {
            get {
                return ResourceManager.GetString("SecurityAnswerInvalidText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security answer value cannot exceed 64 characters..
        /// </summary>
        public static string SecurityAnswerMaximumLength {
            get {
                return ResourceManager.GetString("SecurityAnswerMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security answer value cannot exceed 64 characters..
        /// </summary>
        public static string SecurityAnswerMaximumLength1 {
            get {
                return ResourceManager.GetString("SecurityAnswerMaximumLength1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer missing..
        /// </summary>
        public static string SecurityAnswerMissing {
            get {
                return ResourceManager.GetString("SecurityAnswerMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer missing..
        /// </summary>
        public static string SecurityAnswerMissing1 {
            get {
                return ResourceManager.GetString("SecurityAnswerMissing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a security answer..
        /// </summary>
        public static string SecurityAnswerRequired {
            get {
                return ResourceManager.GetString("SecurityAnswerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a security answer..
        /// </summary>
        public static string SecurityAnswerRequired1 {
            get {
                return ResourceManager.GetString("SecurityAnswerRequired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security question value cannot exceed 64 characters..
        /// </summary>
        public static string SecurityQuestionMaximumLength {
            get {
                return ResourceManager.GetString("SecurityQuestionMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security question value cannot exceed 64 characters..
        /// </summary>
        public static string SecurityQuestionMaximumLength1 {
            get {
                return ResourceManager.GetString("SecurityQuestionMaximumLength1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to reset your password online.  Please contact Patterson Medical on 08448 730 035..
        /// </summary>
        public static string SecurityQuestionMissing {
            get {
                return ResourceManager.GetString("SecurityQuestionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to reset your password online.  Please contact Patterson Medical on 08448 730 035..
        /// </summary>
        public static string SecurityQuestionMissing1 {
            get {
                return ResourceManager.GetString("SecurityQuestionMissing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a security question..
        /// </summary>
        public static string SecurityQuestionRequired {
            get {
                return ResourceManager.GetString("SecurityQuestionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a security question..
        /// </summary>
        public static string SecurityQuestionRequired1 {
            get {
                return ResourceManager.GetString("SecurityQuestionRequired1", resourceCulture);
            }
        }
    }
}
